# Generated by Django 5.2.7 on 2025-10-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_special_instructions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(
                choices=[
                    ('placed', 'Placed'),
                    ('confirmed', 'Confirmed'),
                    ('preparing', 'Preparing'),
                    ('ready', 'Ready'),
                    ('completed', 'Completed'),
                    ('cancelled', 'Cancelled'),
                ],
                default='placed',
                max_length=50
            ),
        ),
    ]